version: '3'

vars:
  CACHE_PATH: ".zig-cache"
  OUTPUT_PATH: "zig-out"

tasks:
  clean:
    cmds:
      - rm -rf {{.CACHE_PATH}} {{.OUTPUT_PATH}}

  build:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig015 cc -o libmath.so -shared -fPIC ../math.c
      - zig015 build-exe ../main.zig -femit-bin=lib-cc-shared -fstrip -lc -L. -lmath -O ReleaseSmall -target native -mcpu=baseline
      - patchelf --replace-needed liblibmath.so ./libmath.so ./lib-cc-shared
      - rm -rf lib-cc-shared.o

  run:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - ./lib-cc-shared {{.CLI_ARGS}}
