#!/bin/bash
#--------------------------------------------------------------------------------
#################################################################################
#--------------------------------------------------------------------------------
ERROR_LOG="error.log"; [ -f "${ERROR_LOG}" ] && rm "${ERROR_LOG}"
#--------------------------------------------------------------------------------
STDOUT=$(mktemp); STDERR=$(mktemp)
#--------------------------------------------------------------------------------
zig-run >"${STDOUT}" 2>"${STDERR}"
#--------------------------------------------------------------------------------
[ -s "${STDOUT}" ] && OUTPUT=$(cat "${STDOUT}"); [ ! -s "${STDOUT}" ] && OUTPUT=$(cat "${STDERR}")
#--------------------------------------------------------------------------------
[[ ! "${OUTPUT}" =~ "compareStringResultError expected_result" ]] && echo "(${LINENO}) compareStringResultError expected_result" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareStringResultError invalid_result" ]] && echo "(${LINENO}) compareStringResultError invalid_result" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareStringResultError error.ExpectedError" ]] && echo "(${LINENO}) compareStringResultError error.ExpectedError" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareStringResultError error.UnexpectedError" ]] && echo "(${LINENO}) compareStringResultError error.UnexpectedError" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareStringSlice pass" ]] && echo "(${LINENO}) compareStringSlice pass" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareStringSlice fail" ]] && echo "(${LINENO}) compareStringSlice fail" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareByteSlice pass" ]] && echo "(${LINENO}) compareByteSlice pass" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareByteSlice fail" ]] && echo "(${LINENO}) compareByteSlice fail" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareByte pass" ]] && echo "(${LINENO}) compareByte pass" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareByte fail" ]] && echo "(${LINENO}) compareByte fail" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareInt pass" ]] && echo "(${LINENO}) compareInt pass" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareInt fail" ]] && echo "(${LINENO}) compareInt fail" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareBool pass" ]] && echo "(${LINENO}) compareBool pass" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareBool fail" ]] && echo "(${LINENO}) compareBool fail" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareError ExpectError" ]] && echo "(${LINENO}) compareError ExpectError" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "compareError InvalidError" ]] && echo "(${LINENO}) compareError InvalidError" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "pass" ]] && echo "(${LINENO}) pass" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "fail" ]] && echo "(${LINENO}) fail" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "errorPass error.ExpectedError" ]] && echo "(${LINENO}) errorPass error.ExpectedError" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "errorFail error.UnexpectedError" ]] && echo "(${LINENO}) errorFail error.UnexpectedError" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "errorExpectedFail error.ExpectedError" ]] && echo "(${LINENO}) errorExpectedFail error.ExpectedError" >> ${ERROR_LOG}
#--------------------------------------------------------------------------------
if [ -f ${ERROR_LOG} ]
then
    cat ${ERROR_LOG} >&2
else
    echo "no errors detected"
fi
#--------------------------------------------------------------------------------
[ -f "${STDOUT}" ] && rm "${STDOUT}"
[ -f "${STDERR}" ] && rm "${STDERR}"
[ -f "${ERROR_LOG}" ] && rm "${ERROR_LOG}"
#--------------------------------------------------------------------------------
exit 0
#--------------------------------------------------------------------------------
#################################################################################
#--------------------------------------------------------------------------------
