version: '3'

vars:
  CACHE_PATH: ".zig-cache"
  OUTPUT_PATH: "zig-out"

tasks:
  clean:
    cmds:
      - rm -rf {{.CACHE_PATH}} {{.OUTPUT_PATH}}

  build:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig015 build-lib ../math.zig -femit-bin=libmath.a -static -fstrip -O ReleaseSmall -target native -mcpu=baseline
      - zig015 build-exe ../main.zig -femit-bin=zigmain -L. -lmath -fstrip -O ReleaseSmall -target native -mcpu=baseline
      - gcc -o cmain ../main.c -L. -lmath -static
      - rm -rf libmath.{a,a.o} zigmain.o

  run:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - ./cmain {{.CLI_ARGS}}
      - ./zigmain {{.CLI_ARGS}}
