version: '3'

vars:
  SOURCE: "main.zig"
  CACHE_PATH: ".zig-cache"
  OUTPUT_PATH: "zig-out"
  OUTPUT:
    sh: |
      if [[ "{{OS}}" == "windows" ]]; then
        echo ${PWD##*\\}
      else
        basename "${PWD}"
      fi

tasks:
  clean:
    cmds:
      - rm -rf {{.CACHE_PATH}} {{.OUTPUT_PATH}}

  build:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig015 build-exe ../{{.SOURCE}} -femit-bin={{.OUTPUT}} -fstrip -O ${ZIG_BUILD_MODE} -target native -mcpu=baseline

  build-linux:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig015 build-exe ../{{.SOURCE}} -femit-bin={{.OUTPUT}} -fstrip -O ${ZIG_BUILD_MODE} -target x86_64-linux -mcpu=baseline

  build-macos:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig015 build-exe ../{{.SOURCE}} -femit-bin={{.OUTPUT}}-darwin -fstrip -O ${ZIG_BUILD_MODE} -target x86_64-macos -mcpu=baseline

  build-windows:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig015 build-exe ../{{.SOURCE}} -femit-bin={{.OUTPUT}}-windows.exe -fstrip -O ${ZIG_BUILD_MODE} -target x86_64-windows -mcpu=baseline

  deploy:
    deps: [build, build-windows]
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - |
        if [ -n "${DEPLOY_PATH_WINDOWS}" ]; then
          cp {{.OUTPUT}}-windows.exe "${DEPLOY_PATH_WINDOWS}/{{.OUTPUT}}-windows.exe"
        fi
      - |
        if [ -n "${DEPLOY_PATH_ZIG}" ]; then
          cp {{.OUTPUT}} "${DEPLOY_PATH_ZIG}/{{.OUTPUT}}"
        fi

  run:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - silent: true
        cmd: |
          if [ -x "{{.OUTPUT}}" ]; then
            ./{{.OUTPUT}} {{.CLI_ARGS}}
          else
            zig015 run ../{{.SOURCE}} -- {{.CLI_ARGS}}
          fi
